apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: my-akkaapi:1.0
          imagePullPolicy: Never  # or IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: CASSANDRA_HOST
              value: cassandra:9042
---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
