#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: cassandra
#  labels:
#    app: cassandra
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: cassandra
#  template:
#    metadata:
#      labels:
#        app: cassandra
#    spec:
#      containers:
#        - name: cassandra
#          image: db:1.0
#          ports:
#            - containerPort: 9042
#              name: cassandra
#          readinessProbe:
#            httpGet:
#              path: /healthz
#              port: 9042
#            initialDelaySeconds: 5
#            periodSeconds: 10
#          livenessProbe:
#            httpGet:
#              path: /healthz
#              port: 9042
#            initialDelaySeconds: 5
#            periodSeconds: 10
#            failureThreshold: 3
#            successThreshold: 1
#          env:
#            - name: CASSANDRA_SEEDS
#              value: cassandra
#        - name: cassandra-load-keyspace
#          image: db:1.0
#          readinessProbe:
#            httpGet:
#              path: /healthz
#              port: 9042
#            initialDelaySeconds: 5
#            periodSeconds: 10
#            tcpSocket:
#              port: 9042
#          command: [ "/bin/bash", "-c" ]
#          args: [ "sleep 100 && echo loading cassandra keyspace && cqlsh cassandra -u cassandra -p cassandra -f /create-table.cql" ]
#          env:
#            - name: WAIT_HOSTS
#              value: "cassandra:9042"
#            - name: WAIT_HOSTS_TIMEOUT
#              value: "300"
#            - name: WAIT_SLEEP_INTERVAL
#              value: "30"
#            - name: WAIT_HOST_CONNECT_TIMEOUT
#              value: "30"
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: cassandra
#  labels:
#    app: cassandra
#spec:
#  type: ClusterIP
#  selector:
#    app: cassandra
#  ports:
#    - protocol: TCP
#      port: 9042
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
      name: cassandra
    spec:
      containers:
        - name: cassandra
          image: db:1.0
          env:
            - name: USERNAME
              value: "cassandra"
            - name: PASSWORD
              value: "cassandra"
          ports:
            - containerPort: 9042
          volumeMounts:
            - name: cassandra-data
              mountPath: /var/lib/cassandra
      volumes:
        - name: cassandra-data
          emptyDir: {}
---
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra
spec:
  selector:
    app: cassandra
  ports:
    - protocol: TCP
      port: 9042
      targetPort: 9042
